// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyCxzC7FaxQQw0wbEtVY1Zojilfb72eka3g',
    appId: '1:757791024952:web:d2701d6c70fde44af2c3cd',
    messagingSenderId: '757791024952',
    projectId: 'project-smartbudget-826b7',
    authDomain: 'project-smartbudget-826b7.firebaseapp.com',
    storageBucket: 'project-smartbudget-826b7.firebasestorage.app',
    measurementId: 'G-HESE19MEDK',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyBo8k2TGg_c2W4CqURgRcENMj6F-d-GVjM',
    appId: '1:757791024952:android:73a6c5024fe29b13f2c3cd',
    messagingSenderId: '757791024952',
    projectId: 'project-smartbudget-826b7',
    storageBucket: 'project-smartbudget-826b7.firebasestorage.app',
  );
  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyA54z8WZiIDE7LWQlJJ3wcFgJaR0nba02w',
    appId: '1:757791024952:ios:435a5c39ad4859ddf2c3cd',
    messagingSenderId: '757791024952',
    projectId: 'project-smartbudget-826b7',
    storageBucket: 'project-smartbudget-826b7.firebasestorage.app',
    iosBundleId: 'com.example.smartBudget',
  );
  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyA54z8WZiIDE7LWQlJJ3wcFgJaR0nba02w',
    appId: '1:757791024952:ios:435a5c39ad4859ddf2c3cd',
    messagingSenderId: '757791024952',
    projectId: 'project-smartbudget-826b7',
    storageBucket: 'project-smartbudget-826b7.firebasestorage.app',
    iosBundleId: 'com.example.smartBudget',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyCxzC7FaxQQw0wbEtVY1Zojilfb72eka3g',
    appId: '1:757791024952:web:5079610c4c6dbbb2f2c3cd',
    messagingSenderId: '757791024952',
    projectId: 'project-smartbudget-826b7',
    authDomain: 'project-smartbudget-826b7.firebaseapp.com',
    storageBucket: 'project-smartbudget-826b7.firebasestorage.app',
    measurementId: 'G-S0TE22BC8D',
  );
}
